import { Campaign } from "@/app/(protected)/dashboard/automate/types";

// Demo data for the dashboard
export const demoMetrics = {
  totalImported: 3247,
  totalSent: 2156,
  accepted: 1089,
  pending: 523,
  acceptanceRate: 50.5,
  responseRate: 41.8,
  totalMessages: 1432,
  messageConversionRate: 66.4,
  dailyAverage: 38,
  weeklyGrowth: 12.3,
  weeklyData: [178, 192, 167, 203, 218, 225, 201], // Last 7 days of connection activity
};

export const demoCampaigns: Campaign[] = [
  {
    id: 1,
    name: "Enterprise Security Leaders",
    trending: "yes",
    searchQuery: "CISO, Chief Security Officer, VP Security",
    startDate: "2024-04-01",
    endDate: "2024-05-01",
    sent: 542,
    accepted: 234,
    pending: 98,
    invited: 542,
    responseRate: 43.2,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=ciso%20chief%20security%20officer",
    connection_message: "Hi {{firstName}}, your cybersecurity expertise caught my attention. Would love to connect and discuss how AI is revolutionizing enterprise security.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about next-gen security solutions that might interest you. Would you be open to a brief conversation?",
    second_follow_up_message: "Just following up - I have some exciting developments in AI-powered security that could be relevant to your organization.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-04-01",
    end_date: "2024-05-01"
  },
  {
    id: 2,
    name: "Climate Tech Investors",
    trending: "yes",
    searchQuery: "Climate investor, GreenTech VC, Sustainability partner",
    startDate: "2024-04-10",
    endDate: "2024-05-10",
    sent: 387,
    accepted: 189,
    pending: 56,
    invited: 387,
    responseRate: 48.8,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=climate%20investor%20cleantech%20vc",
    connection_message: "Hi {{firstName}}, your work in climate tech investing is inspiring. Would love to connect and explore potential synergies in sustainable innovation.",
    follow_up_message: "Thanks for connecting! I'm working on some exciting climate tech solutions that might align with your investment focus. Would you be interested in learning more?",
    second_follow_up_message: "Just checking in - I'd love to share how we're building the next generation of climate solutions. Any interest in a quick chat?",
    follow_up_days: 3,
    second_follow_up_days: 5,
    cancelled: 0,
    start_date: "2024-04-10",
    end_date: "2024-05-10"
  },
  {
    id: 3,
    name: "Healthcare Innovation Leaders",
    trending: "no",
    searchQuery: "Healthcare CTO, Medical Device VP, HealthTech Director",
    startDate: "2024-03-15",
    endDate: "2024-04-15",
    sent: 456,
    accepted: 198,
    pending: 67,
    invited: 456,
    responseRate: 43.4,
    status: "completed",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=healthcare%20cto%20medical%20device",
    connection_message: "Hi {{firstName}}, your healthcare innovation work is impressive. Would love to connect and discuss how AI is transforming patient care.",
    follow_up_message: "Thanks for connecting! I'd love to share how we're helping healthcare leaders leverage AI for better patient outcomes.",
    second_follow_up_message: "Quick follow-up - would you be interested in learning about our AI-driven healthcare solutions?",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-03-15",
    end_date: "2024-04-15"
  },
  {
    id: 4,
    name: "Founders & CEOs",
    trending: "yes",
    searchQuery: "Founder, CEO, Co-founder, Startup CEO",
    startDate: "2024-04-15",
    endDate: "2024-05-15",
    sent: 298,
    accepted: 156,
    pending: 42,
    invited: 298,
    responseRate: 52.3,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=founder%20ceo%20startup",
    connection_message: "Hi {{firstName}}, your entrepreneurial journey is inspiring. Would love to connect and share insights about scaling innovative ventures.",
    follow_up_message: "Thanks for connecting! I'd love to discuss how we're helping founders accelerate growth. Would you be interested in a brief conversation?",
    second_follow_up_message: "Quick follow-up - I have some exciting strategies for startup scaling that might be relevant to your venture.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-04-15",
    end_date: "2024-05-15"
  },
  {
    id: 5,
    name: "FinTech Executives",
    trending: "no",
    searchQuery: "FinTech VP, Financial Services Director, Banking CTO",
    startDate: "2024-03-20",
    endDate: "2024-04-20",
    sent: 234,
    accepted: 98,
    pending: 34,
    invited: 234,
    responseRate: 41.9,
    status: "completed",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=fintech%20financial%20services%20banking",
    connection_message: "Hi {{firstName}}, your fintech expertise caught my attention. Would love to connect and discuss the future of digital finance.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about innovative financial solutions that might interest you.",
    second_follow_up_message: "Just following up - I have some exciting developments in fintech that could be relevant to your organization.",
    follow_up_days: 3,
    second_follow_up_days: 5,
    cancelled: 0,
    start_date: "2024-03-20",
    end_date: "2024-04-20"
  },
  {
    id: 6,
    name: "AI & ML Leaders",
    trending: "yes",
    searchQuery: "AI Director, Machine Learning VP, Data Science Head",
    startDate: "2024-04-05",
    endDate: "2024-05-05",
    sent: 189,
    accepted: 87,
    pending: 23,
    invited: 189,
    responseRate: 46.0,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=ai%20machine%20learning%20data%20science",
    connection_message: "Hi {{firstName}}, your AI and ML work is impressive. Would love to connect and explore cutting-edge developments in artificial intelligence.",
    follow_up_message: "Thanks for connecting! I'd love to discuss how we're advancing AI solutions. Would you be interested in learning more?",
    second_follow_up_message: "Quick follow-up - I have some exciting AI innovations that might align with your work.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-04-05",
    end_date: "2024-05-05"
  },
  {
    id: 7,
    name: "E-commerce Leaders",
    trending: "no",
    searchQuery: "E-commerce Director, Online Retail VP, Digital Commerce Head",
    startDate: "2024-03-10",
    endDate: "2024-04-10",
    sent: 167,
    accepted: 72,
    pending: 28,
    invited: 167,
    responseRate: 43.1,
    status: "completed",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=ecommerce%20online%20retail%20digital%20commerce",
    connection_message: "Hi {{firstName}}, your e-commerce expertise is impressive. Would love to connect and discuss the future of online retail.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about innovative e-commerce solutions that might interest you.",
    second_follow_up_message: "Just following up - I have some exciting developments in digital commerce that could be relevant to your business.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-03-10",
    end_date: "2024-04-10"
  },
  {
    id: 8,
    name: "SaaS Executives",
    trending: "yes",
    searchQuery: "SaaS VP, Software Director, Product Head",
    startDate: "2024-04-20",
    endDate: "2024-05-20",
    sent: 143,
    accepted: 68,
    pending: 19,
    invited: 143,
    responseRate: 47.6,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=saas%20software%20product%20management",
    connection_message: "Hi {{firstName}}, your SaaS expertise caught my attention. Would love to connect and discuss scaling software businesses.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about SaaS growth strategies that might interest you.",
    second_follow_up_message: "Quick follow-up - I have some exciting SaaS innovations that could be relevant to your company.",
    follow_up_days: 3,
    second_follow_up_days: 5,
    cancelled: 0,
    start_date: "2024-04-20",
    end_date: "2024-05-20"
  },
  {
    id: 9,
    name: "Marketing Leaders",
    trending: "no",
    searchQuery: "CMO, Marketing VP, Brand Director",
    startDate: "2024-03-25",
    endDate: "2024-04-25",
    sent: 134,
    accepted: 58,
    pending: 21,
    invited: 134,
    responseRate: 43.3,
    status: "completed",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=cmo%20marketing%20brand%20director",
    connection_message: "Hi {{firstName}}, your marketing expertise is impressive. Would love to connect and discuss innovative marketing strategies.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about cutting-edge marketing solutions that might interest you.",
    second_follow_up_message: "Just following up - I have some exciting marketing innovations that could be relevant to your brand.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-03-25",
    end_date: "2024-04-25"
  },
  {
    id: 10,
    name: "Sales Leaders",
    trending: "yes",
    searchQuery: "VP Sales, Sales Director, Revenue Head",
    startDate: "2024-04-12",
    endDate: "2024-05-12",
    sent: 128,
    accepted: 61,
    pending: 17,
    invited: 128,
    responseRate: 47.7,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=vp%20sales%20sales%20director%20revenue",
    connection_message: "Hi {{firstName}}, your sales leadership is impressive. Would love to connect and discuss revenue growth strategies.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about sales acceleration that might interest you.",
    second_follow_up_message: "Quick follow-up - I have some exciting sales innovations that could be relevant to your team.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-04-12",
    end_date: "2024-05-12"
  },
  {
    id: 11,
    name: "Product Leaders",
    trending: "no",
    searchQuery: "CPO, Product VP, Product Director",
    startDate: "2024-03-30",
    endDate: "2024-04-30",
    sent: 112,
    accepted: 48,
    pending: 16,
    invited: 112,
    responseRate: 42.9,
    status: "completed",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=cpo%20product%20vp%20product%20director",
    connection_message: "Hi {{firstName}}, your product expertise caught my attention. Would love to connect and discuss product innovation strategies.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about product development that might interest you.",
    second_follow_up_message: "Just following up - I have some exciting product innovations that could be relevant to your roadmap.",
    follow_up_days: 3,
    second_follow_up_days: 5,
    cancelled: 0,
    start_date: "2024-03-30",
    end_date: "2024-04-30"
  },
  {
    id: 12,
    name: "HR & Talent Leaders",
    trending: "yes",
    searchQuery: "CHRO, VP People, Talent Director",
    startDate: "2024-04-25",
    endDate: "2024-05-25",
    sent: 97,
    accepted: 44,
    pending: 13,
    invited: 97,
    responseRate: 45.4,
    status: "active",
    campaign_type: "search",
    linkedin_url: "https://linkedin.com/search/results/people/?keywords=chro%20vp%20people%20talent%20director",
    connection_message: "Hi {{firstName}}, your HR and talent expertise is impressive. Would love to connect and discuss people strategy.",
    follow_up_message: "Thanks for connecting! I'd love to share insights about talent acquisition that might interest you.",
    second_follow_up_message: "Quick follow-up - I have some exciting HR innovations that could be relevant to your organization.",
    follow_up_days: 2,
    second_follow_up_days: 4,
    cancelled: 0,
    start_date: "2024-04-25",
    end_date: "2024-05-25"
  }
];

export const demoActivities = [
  {
    id: "act-1",
    type: "connection",
    message: "Dr. Maria Santos (CISO at MedTech Solutions) accepted your connection request",
    timestamp: new Date(Date.now() - 1800000).toISOString(), // 30 mins ago
    status: "accepted",
  },
  {
    id: "act-2",
    type: "message",
    message: "Received reply from James Park (Partner at GreenVentures)",
    timestamp: new Date(Date.now() - 3600000).toISOString(), // 1 hour ago
    status: "received",
  },
  {
    id: "act-3",
    type: "connection",
    message: "Connection request sent to Dr. Rachel Kim (VP of Innovation at HealthFirst)",
    timestamp: new Date(Date.now() - 7200000).toISOString(), // 2 hours ago
    status: "pending",
  },
  {
    id: "act-4",
    type: "message",
    message: "Message sent to Alex Chen (Security Architect at SecureNet)",
    timestamp: new Date(Date.now() - 10800000).toISOString(), // 3 hours ago
    status: "sent",
  }
];